[package]
name = "nucleus"
version = "0.1.0"
edition = "2024"
authors = ["Enzo Blain <enzoblain@proton.me>"]
description = "Low-level system crate for the Nebula ecosystem — cross-platform abstraction over OS system calls"
repository = "https://github.com/Nebula-ecosystem/Nucleus"
license = "SSPL-1.0"
keywords = ["nebula", "system", "syscalls", "io", "async"]
categories = ["os", "network-programming", "asynchronous"]

[dependencies]
libc = "0.2.180"
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_System_IO",
    "Win32_Networking_WinSock",
    "Win32_Storage_FileSystem",
    "Win32_Security"
] }